### ISSUE TITLE
Github-Actions CI for Forks

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#702]
When contributors fork the repo, they can't use our github-actions based CI because it has has the repo-name hard-coded in update.sh.

Making an issue to track this before I forget. I think we should also change it to:
1) Use Github's actions/checkout to clone the repo instead of the git pull hacks in update.sh
2) Use Github's actions/cache to cache containers locally (if it's faster than pulling from dockerhub) and share between CI jobs/steps

**Comment by AndrewFasano** [comment]
A surprising result I've discovered is that using Github's cache with `docker save` and `docker load` appears to be slower than just doing a `docker pull`.

For instance, the following code takes 2:30 to restore from the cache, 4:45 to `docker load` and then just 0:41 to run make (when no source is modified). On the other hand, doing a `docker pull` from Dockerhub takes ~ 1:45.

```
name: Docker Build - Incremental

on:
  push:
    branches-ignore:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Get hash of latest PANDA container on Dockerhub # Somehow these quotes actually work
      run: echo "::set-env name=latesthash::$(curl  -s -S 'https://registry.hub.docker.com/v2/repositories/pandare/panda/tags/' | jq -cr '."results"[1]["name"]')"

    - name: Check cache for latest docker container
      uses: actions/cache@v2
      id: cache
      env:
        cache-name: cache-docker-bionic
      with:
        path: /home/runner/panda.container
        key: ${{ env.latesthash }}

    - name: (Cache miss) Fetch docker container # If not cached, grab the container and export it to disk
      if: steps.cache.outputs.cache-hit != 'true'
      run: "docker pull pandare/panda:latest && docker save pandare/panda > /home/runner/panda.container"

    - name: (Cache hit) Load cached docker container # Cache hit - load from cache
      if: steps.cache.outputs.cache-hit == 'true'
      run: "docker load < /home/runner/panda.container"

    - uses: actions/checkout@v1

      # Map new code into container (checkout action clones this commit to /home/runner/work/panda)
      # and run new new update.sh script
    - name: Map code into container and run update.sh to rebuild and test
      run: docker run --rm -v /home/runner/work/panda/panda/:/panda.new pandare/panda bash /panda.new/panda/docker/update.sh
```
